"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_spectacular',

    # Local apps — Person 1 (Omar): accounts & roles
    'accounts',
    # Local apps — Person 2 (Aya): sales/deal lifecycle, payments & financing, reporting
    'sales',
    'payments',
    'reports',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# -----------------------------------------------------------------------
# Django REST Framework
# API conventions (see ADMS_API_Specification.md):
#   - Base URL: /api/v1
#   - Auth: Bearer JWT
#   - Pagination: { "count", "next", "previous", "results": [...] }
#   - Errors: { "error": { "code", "message", "fields": {...} } }
# -----------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'EXCEPTION_HANDLER': 'common.exceptions.standard_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Disabled: DRF's built-in `?format=` override collides with the API
    # spec's own use of `?format=csv` on /reports/payments/export (DRF
    # would try to content-negotiate a "csv" renderer and 404/406 instead
    # of reaching the view). No other endpoint in the spec relies on DRF's
    # format-suffix switching, so this is safe to turn off globally.
    'URL_FORMAT_OVERRIDE': None,
}

# -----------------------------------------------------------------------
# drf-spectacular (OpenAPI schema + Swagger UI / ReDoc)
# Served at /api/v1/schema, /api/v1/docs (Swagger UI), /api/v1/redoc
# See config/urls.py for the mounted routes.
# -----------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    'TITLE': 'AutoSource ADMS API',
    'DESCRIPTION': (
        'Automotive Dealership Management System API.\n\n'
        'This schema currently documents Person 2\'s scope: Trade-Ins, '
        'Sales Invoices / Deals, Tax Rules, Payments, Payment Schedules, '
        'Financing Accounts, Statements, Dashboard, Finance & Reports, '
        'and the Audit Log. Person 1\'s endpoints (Authentication, Users '
        '& Roles, Vendors, Purchase Orders, Vehicles, Documents, '
        'Customers) will appear here automatically once that app is '
        'merged, since they share the same DRF schema generator — no '
        'extra wiring needed on either side.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/v1/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'TAGS': [
        {'name': 'Trade-Ins', 'description': 'Trade-in appraisal and crediting.'},
        {'name': 'Tax Rules', 'description': 'Admin-configured tax rates.'},
        {'name': 'Sales Invoices', 'description': 'The deal / invoice lifecycle.'},
        {'name': 'Payments', 'description': 'Recording payments and receipts.'},
        {'name': 'Payment Schedules', 'description': 'Installment schedules.'},
        {'name': 'Financing Accounts', 'description': 'Financing agreements (1:1 with an invoice).'},
        {'name': 'Statements', 'description': 'Customer statements.'},
        {'name': 'Dashboard', 'description': 'Aggregate KPI cards for the staff dashboard.'},
        {'name': 'Finance & Reports', 'description': 'Finance overview and per-vehicle summaries.'},
        {'name': 'Audit Log', 'description': 'Internal audit trail (admin-only).'},
    ],
    # Several models have a "status" field with different choice sets
    # (SalesInvoice, PaymentSchedule, FinancingAccount, AuditLog.action) --
    # name each enum explicitly so Swagger doesn't auto-generate ambiguous
    # names like "StatusDdfEnum".
    'ENUM_NAME_OVERRIDES': {
        'SalesInvoiceStatusEnum': 'sales.models.SalesInvoice.STATUS_CHOICES',
        'PaymentScheduleStatusEnum': 'payments.models.PaymentSchedule.STATUS_CHOICES',
        'FinancingAccountStatusEnum': 'payments.models.FinancingAccount.STATUS_CHOICES',
    },
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Role checks (admin / agent / accountant) read from Person 1's
# accounts.UserProfile.role with a Django Groups fallback — see
# common/permissions.py. Superuser always passes every role check.
