# Generated by Django 6.1 on 2026-09-05 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_vehicle_vehiclemedia_vehiclevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_type', models.CharField(choices=[('VEHICLE', 'Vehicle'), ('CUSTOMER', 'Customer'), ('INVOICE', 'Invoice')], max_length=20)),
                ('related_id', models.IntegerField()),
                ('doc_type', models.CharField(choices=[('TITLE', 'Title'), ('ID', 'ID'), ('CONTRACT', 'Contract'), ('INSPECTION', 'Inspection'), ('BILL_OF_SALE', 'Bill of Sale')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
