# Generated by Django 6.1 on 2026-09-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=60)),
                ('rate', models.DecimalField(decimal_places=4, help_text='e.g. 0.0625 for 6.25%', max_digits=5)),
                ('applies_to', models.CharField(choices=[('VEHICLE_TYPE', 'Vehicle Type'), ('TRANSACTION_TYPE', 'Transaction Type')], default='TRANSACTION_TYPE', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['jurisdiction'],
            },
        ),
    ]
