# Generated by Django 6.1 on 2026-09-03 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentschedule'),
        ('sales', '0003_remove_tradein_credited_invoice_id_salesinvoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='financing_account_id',
        ),
        migrations.CreateModel(
            name='FinancingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(blank=True, max_length=120)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('term_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='e.g. 0.0599 for 5.99%', max_digits=5)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('DEFAULT', 'Default')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financing_account', to='sales.salesinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='financing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.financingaccount'),
        ),
    ]
