# Generated by Django 6.1 on 2026-09-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_financing_account_id_financingaccount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financingaccount',
            options={'ordering': ['-created_at']},
        ),
    ]
